### ISSUE TITLE
SFXBean update problems

### ISSUE THREAD

**Issue by ASchmidt84** [sfxcode/sapphire-javafx#23]
Hi,

I have da FX DataType like that
```
case class PatientViewFX(number: String,
                         postalAddress: PostalAddressFX)

case class PostalAddressFX(addressLine1: String,
                           addressLine2: String,
                           streetLine: String,
                           postalCode: String,
                           city: String,
                           state: String,
                           countryLine: CountryFX)

case class CountryFX(isoCode: String)
```
I use it like 
```
SFXBean(PatientViewFX(.....))
```
All works fine. But I use now an adapter. I want the same "update" function for countryLine as for any string value.

in my property sheet I use it like this
```
beanItems.addItem("postalAddress.countryLine",i18n("patient.postalAddress.country"),i18n("patient.title.address"),clazz = classOf[CountryFX])
```
All the time the other string values on property sheet are correctly changed but not the countryFX. the addressLine1 is correct and all other things:
```
{com.sfxcode.sapphire.javafx.value.SFXBean@85afb42 : PatientViewFX(,PersonalDataFX(,,),PostalAddressFX(ICh,Du,Straße 1,12345,Ort,Bundesland,Deutschland)[...]
```
But country should be now Tscad. 
where is my mistake?
Thank you

**Comment by ASchmidt84** [comment]
I added some code to find out where the issue could be lay.
My PropertyEditor is build here:
```
object CustomPropertyEditors {

  def createCountryFXComboboxEditor(item: Item): AbstractPropertyEditor[CountryFX,jfsc.ComboBox[CountryFX]] = {
    val box = new ComboBox[CountryFX]()
    box.items() ++= CountryFX.allLocale
    box.selectionModel().select(CountryFX("de"))
    box.selectionModel().selectedItem.onChange((_,_,e) => {
      println(s"Change in bx: ${e} in item: ${item.getValue}")
    })

    new AbstractPropertyEditor[CountryFX,jfsc.ComboBox[CountryFX]](item,box){

      override def getObservableValue: ObservableValue[CountryFX] = {
        println( "a: " + getEditor.selectionModel().selectedItem )
        println( "b: " + box.selectionModel().selectedItem )
        getEditor.getSelectionModel.selectedItemProperty()
      }

      override def setValue(value: CountryFX): Unit = {
        if(value != null) {
          box.selectionModel().select(value)
        }
      }
    }

  }

}
```
On first start and a change you can see that in output:
```
a: [SFX]ReadOnlyObjectProperty [bean: javafx.scene.control.ComboBox$ComboBoxSelectionModel@21325c33, name: selectedItem, value: Deutschland]
b: [SFX]ReadOnlyObjectProperty [bean: javafx.scene.control.ComboBox$ComboBoxSelectionModel@21325c33, name: selectedItem, value: Deutschland]
Change in bx: Deutschland in item: Deutschland
a: [SFX]ReadOnlyObjectProperty [bean: javafx.scene.control.ComboBox$ComboBoxSelectionModel@21325c33, name: selectedItem, value: Deutschland]
b: [SFX]ReadOnlyObjectProperty [bean: javafx.scene.control.ComboBox$ComboBoxSelectionModel@21325c33, name: selectedItem, value: Deutschland]
Change in bx: Jamaika in item: Deutschland
a: [SFX]ReadOnlyObjectProperty [bean: javafx.scene.control.ComboBox$ComboBoxSelectionModel@21325c33, name: selectedItem, value: Jamaika]
b: [SFX]ReadOnlyObjectProperty [bean: javafx.scene.control.ComboBox$ComboBoxSelectionModel@21325c33, name: selectedItem, value: Jamaika]
CHANGED Deutschland
CHANGED Deutschland
```
And this is in my controller
```
override def didGainVisibilityFirstTime(): Unit = {
    super.didGainVisibilityFirstTime()

    beanItems.addItem("postalAddress.addressLine1",i18n("patient.postalAddress.addressLine1"),i18n("patient.title.address"))
    beanItems.addItem("postalAddress.addressLine2",i18n("patient.postalAddress.addressLine2"),i18n("patient.title.address"))
    beanItems.addItem("postalAddress.streetLine",i18n("patient.postalAddress.street"),i18n("patient.title.address"))
    beanItems.addItem("postalAddress.postalCode",i18n("patient.postalAddress.zip"),i18n("patient.title.address"))
    beanItems.addItem("postalAddress.city",i18n("patient.postalAddress.place"),i18n("patient.title.address"))
    beanItems.addItem("postalAddress.state",i18n("patient.postalAddress.state"),i18n("patient.title.address"))
    beanItems.addItem("postalAddress.countryLine",i18n("patient.postalAddress.country"),i18n("patient.title.address"),clazz = classOf[CountryFX])

    rootDataPropertySheet.setPropertyEditorFactory( (item: PropertySheet.Item) => {
      item.getType match {
        case x if x == classOf[CountryFX] =>
          CustomPropertyEditors.createCountryFXComboboxEditor(item)
        case _ =>
          new DefaultPropertyEditorFactory().call(item)
      }
    } )

    this.applicationController.mainSFXViewController.patientWorkspace.patient.onChange((_,_,e) => {
      adapter.set(e)
      beanItems.updateBean(e)
      beanItems.getItems.foreach(a => println(a.getKey))
      beanItems.getItems.find(_.getKey == "postalAddress.countryLine").get.getObservableValue().get().onChange((_,_,e) => {
        println("CHANGED " + e)
      })
      rootDataPropertySheet.getItems.setAll(beanItems.getItems)
    })
  }
```

it looks like that the changement never goes to the item. alway it is only a locale changement.

**Comment by ASchmidt84** [comment]
Okay i figured out that the problem seems not be the property sheet and the editor. It looks like the SFXBean.
Please checkout this
``` 
val test = SFXBean(PatientViewFX())
    println(s"test: ${test.postalAddress.countryLine}")
    test.updateValue("postalAddress.countryLine",CountryFX("us"))
    println(s"test after update: ${test.postalAddress.countryLine}")
```
the output is:
```
test: Deutschland
test after update: Deutschland
```

**Comment by sfxcode** [comment]
Hi,

thanks for your input. I will try to investigate.

Greetings,

Tom

**Comment by ASchmidt84** [comment]
Hi Tom,
thank you. 
I am a little bit frustrated. I try to write a bypass with this
```
beanItems.addItem("postalAddress.countryLine.isoCode",i18n("patient.postalAddress.country"),i18n("patient.title.address") )
```
```
rootDataPropertySheet.setPropertyEditorFactory( (item: PropertySheet.Item) => {
      Try(item.asInstanceOf[BeanItem]) match {
        case Success(f) if f.getKey == "postalAddress.countryLine.isoCode" =>
          CustomPropertyEditors.createCountryFXComboboxEditorString(f)
        case _ =>
          new DefaultPropertyEditorFactory().call(item)
      }
    } )
```
```
def createCountryFXComboboxEditorString(item: BeanItem): AbstractPropertyEditor[String,jfsc.ComboBox[CountryFX]] = {
    val box = new ComboBox[CountryFX]()
    box.items() ++= CountryFX.allLocale
    val isoCodeProperty = new StringProperty()
    box.selectionModel().selectedItem.onChange((_,_,e) => {
      if(e != null){
        isoCodeProperty.value = e.isoCode
      }
    })

    new AbstractPropertyEditor[String,jfsc.ComboBox[CountryFX]](item,box){
      override def getObservableValue: ObservableValue[String] = isoCodeProperty

      override def setValue(value: String): Unit = {
        box.selectionModel().select(CountryFX(value.trim))
      }
    }

  }
```
To change the inner value of countryfx but now I get a compiler error.
```
Exception in thread "JavaFX Application Thread" javax.el.PropertyNotFoundException: Property [countryLine] not found on type [core.adt.PostalAddressFX]
	at javax.el.BeanELResolver$BeanProperties.get(BeanELResolver.java:254)
	at javax.el.BeanELResolver$BeanProperties.access$300(BeanELResolver.java:206)
....
```
Aaaaaaahhhh 😱 😄  I want running aroud and knock my head at the walls i encouter 🤣

**Comment by ASchmidt84** [comment]
What means that
```
Property [name_ignored] not found on type [core.adt.PatientViewFX]
``` 
If i change the status (only that) i get this error. 😢

**Comment by sfxcode** [comment]
Hi,

I can reproduce your problem. Seems that Expression Introspection fails for second level.

I have dig into sapphire-data.

Can take a while ...

**Comment by ASchmidt84** [comment]
Hi Tom,
can i help you?

What do you suggest for a short (in this case also a dirty is acceptable) bypass? 

André

**Comment by sfxcode** [comment]
Quick and dirty solution is skip the second level ...

```case class PostalAddressFX(
  addressLine1: String,
  addressLine2: String,
  streetLine: String,
  postalCode: String,
  city: String,
  state: String,
  isoCode: String)
````

**Comment by ASchmidt84** [comment]
Thats is not only quick and dirty it is also painful 😆 
Okay I will see to write an exchange class 😢

**Comment by sfxcode** [comment]
I will try to fix the problem, but i have to dive into Expression Language under my framework ...
Meanwhile i have made a new demo project, https://github.com/sfxcode/sapphire-jfoenix-demo, to test page transition and other stuff, maybe there is something useful for you ;-)

Tom

**Comment by ASchmidt84** [comment]
oh yes, that sounds very interessting. I will dive also into your demo. I hope you can fix it fast :)
Thank you

André

**Comment by ASchmidt84** [comment]
Tom their is something for you to see.
I change a little bit and setup an bypass class
```
case class PatientBypassView(postalAddressCountryLine: CountryFX)

object PatientBypassView {

  def apply(x: PatientViewFX): PatientBypassView = new PatientBypassView(
    x.postalAddress.countryLine
  )

}
```
Here to see what bindings
```
beanItems.addItem("postalAddressCountryLine",i18n("patient.postalAddress.country"),i18n("patient.title.address"), clazz = classOf[CountryFX] )

def executeSave(): Unit = {
    println(adapter.get)
    println(beanItems.bean)
  }
```
this should be the first level. And this is still the result
```
Change in bx: Niue in item: Deutschland
a: [SFX]ReadOnlyObjectProperty [bean: javafx.scene.control.ComboBox$ComboBoxSelectionModel@31f0eb37, name: selectedItem, value: Niue]
b: [SFX]ReadOnlyObjectProperty [bean: javafx.scene.control.ComboBox$ComboBoxSelectionModel@31f0eb37, name: selectedItem, value: Niue]
c: Deutschland
{com.sfxcode.sapphire.javafx.value.SFXBean@23dfc299 : PatientBypassView(Deutschland)@-1220642565}
{com.sfxcode.sapphire.javafx.value.SFXBean@5709b71c : PatientBypassView(Deutschland)@-1220642565}
```
it looks like that the object is never be exchange. On case class their is always the copy method. Mabe this will never call on other datatypes like the defined.
What do you thing?

**Comment by ASchmidt84** [comment]
Here is more interessting stuff.
```
beanItems.addItem("postalAddressCountryLine.isoCode",i18n("patient.postalAddress.country"),i18n("patient.title.address"), clazz = classOf[String] )
```
and change 
```
rootDataPropertySheet.setPropertyEditorFactory( (item: PropertySheet.Item) => {
      println("item: " + item)
      val beanItem = item.asInstanceOf[BeanItem]
      beanItem.getKey match {
        case "postalAddressCountryLine.isoCode" =>
          CustomPropertyEditors.createCountryFXComboboxEditorString(beanItem)
        case _ =>
          new DefaultPropertyEditorFactory().call(item)
      }


//      item.getType match {
//        case x if x == classOf[CountryFX] =>
//          CustomPropertyEditors.createCountryFXComboboxEditor(item)
//        case x if x == classOf[PatientStatus] =>
//          CustomPropertyEditors.createPatientStatusComboboxEditor(item, (s: String) => i18n(s))
//        case _ =>
//          new DefaultPropertyEditorFactory().call(item)
//      }
    } )
```

produces a change
```
item: com.sfxcode.sapphire.javafx.property.BeanItem@1e7b0eb7
{com.sfxcode.sapphire.javafx.value.SFXBean@1e0d27fc : PatientBypassView(Singapur)@-499621715}
{com.sfxcode.sapphire.javafx.value.SFXBean@5994c9ed : PatientBypassView(Singapur)@-499621715}
```
even it is in the second level.
Still the error if i change back and got to the thir level.
```
postalAddress.countryLine.isoCode
```
produces all the time 
`` 
Exception in thread "JavaFX Application Thread" javax.el.PropertyNotFoundException: Property [countryLine] not found on type [core.adt.PostalAddressFX]
	at javax.el.BeanELResolver$BeanProperties.get(BeanELResolver.java:254)
	at javax.el.BeanELResolver$BeanProperties.access$300(BeanELResolver.java:206)
	at javax.el.BeanELResolver.property(BeanELResolver.java:327)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:86)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
```

**Comment by sfxcode** [comment]
H iAndré,

first problem seems to be fixed now in sapphire-data.

```
    "get child values" in {
      val testBean = DataAdapter[ParentBean](ParentBean())

      testBean.getValue("child.childName") must be equalTo "childName"

      testBean.getValue("child.address").toString must be equalTo "Address(street,12345)"

      testBean.getValue("child.address.street").toString must be equalTo "street"

    }

    "update child values" in {
      val testBean = DataAdapter[ParentBean](ParentBean())

      testBean.getValue("child.address.street").toString must be equalTo "street"

      testBean.updateValue("child.address.street", "newStreet")

      testBean.getValue("child.address.street").toString must be equalTo "newStreet"

      testBean.hasChanges must beTrue
```

works now.

**Comment by sfxcode** [comment]
You can try 
```
dependencyOverrides += "com.sfxcode.sapphire" %% "sapphire-data" % "1.0.6"
```
on your project.

Maybe it is helpful.

Please give it a try and tell me if it works ...

Greetings,

Tom

**Comment by ASchmidt84** [comment]
I will give it a try

**Comment by ASchmidt84** [comment]
I have now the 1.0.6
here
```
println(e)
      e.updateValue("postalAddress.countryLine",CountryFX("us"))
      println(e)
```
result
```
{com.sfxcode.sapphire.javafx.value.SFXBean@7eb6b082 : PatientViewFX(,PersonalDataFX(,,),PostalAddressFX(,,,,,,Deutschland),LocalDateFX(1970-01-01),EmailAddressFX(),inactive,PhoneNumberFX(),PhoneNumberFX(),PhoneNumberFX(),PhoneNumberFX(),,PatientPictureFX(None,),Keine Angabe)@-914360757}
{com.sfxcode.sapphire.javafx.value.SFXBean@7eb6b082 : PatientViewFX(,PersonalDataFX(,,),PostalAddressFX(,,,,,,Deutschland),LocalDateFX(1970-01-01),EmailAddressFX(),inactive,PhoneNumberFX(),PhoneNumberFX(),PhoneNumberFX(),PhoneNumberFX(),,PatientPictureFX(None,),Keine Angabe)@-914360757}
```

You see in both "Deutschland". 
An another test
```
println("---------")
      println(e)
      e.updateValue("postalAddress.countryLine",CountryFX("us"))
      println(e)
      println("---------")
      println(adapter.getValue("postalAddress.countryLine"))
      adapter.updateValue("postalAddress.countryLine",CountryFX("au"))
      println(adapter.getValue("postalAddress.countryLine"))
      println("----------")
```
runs in that
```
---------
{com.sfxcode.sapphire.javafx.value.SFXBean@240dcd91 : PatientViewFX(,PersonalDataFX(,,),PostalAddressFX(,,,,,,Deutschland),LocalDateFX(1970-01-01),EmailAddressFX(),inactive,PhoneNumberFX(),PhoneNumberFX(),PhoneNumberFX(),PhoneNumberFX(),,PatientPictureFX(None,),Keine Angabe)@-914360757}
{com.sfxcode.sapphire.javafx.value.SFXBean@240dcd91 : PatientViewFX(,PersonalDataFX(,,),PostalAddressFX(,,,,,,Deutschland),LocalDateFX(1970-01-01),EmailAddressFX(),inactive,PhoneNumberFX(),PhoneNumberFX(),PhoneNumberFX(),PhoneNumberFX(),,PatientPictureFX(None,),Keine Angabe)@-914360757}
---------
Exception in thread "JavaFX Application Thread" javax.el.PropertyNotFoundException: Property [postalAddress] not found on type [com.sfxcode.sapphire.javafx.value.SFXBeanAdapter]
	at javax.el.BeanELResolver$BeanProperties.get(BeanELResolver.java:254)
	at javax.el.BeanELResolver$BeanProperties.access$300(BeanELResolver.java:206)
	at javax.el.BeanELResolver.property(BeanELResolver.java:327)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:86)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
	at com.sfxcode.sapphire.data.el.Expressions$.getValue(Expressions.scala:26)
	at com.sfxcode.sapphire.data.el.ObjectExpressionHelper$.getValueOnObject(ObjectExpressionHelper.scala:45)
	at com.sfxcode.sapphire.data.el.ObjectExpressionHelper$.getValue(ObjectExpressionHelper.scala:35)
	at com.sfxcode.sapphire.data.el.Expressions$.evaluateExpressionOnObject(Expressions.scala:39)
	at com.sfxcode.sapphire.data.DataAdapter.getValue(DataAdapter.scala:49)
	at com.sfxcode.sapphire.data.DataAdapter.getValue(DataAdapter.scala:45)
	at api.controller.workspaces.PatientRootDataWorkspaceController.$anonfun$didGainVisibilityFirstTime$3(PatientRootDataWorkspaceController.scala:99)
	at api.controller.workspaces.PatientRootDataWorkspaceController.$anonfun$didGainVisibilityFirstTime$3$adapted(PatientRootDataWorkspaceController.scala:88)
	at scalafx.beans.value.ObservableValue$$anon$1.changed(ObservableValue.scala:116)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at scalafx.beans.property.ObjectProperty.value_$eq(ObjectProperty.scala:167)
	at api.controller.navigationBar.RibbonNaviController.createNewPatient(RibbonNaviController.scala:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1782)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1670)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8885)
	at javafx.scene.control.Button.fire(Button.java:203)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3890)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1885)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2618)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

![grafik](https://user-images.githubusercontent.com/5076186/111881988-61545480-89b3-11eb-802d-ce7a717d48f2.png)

**Comment by sfxcode** [comment]
can you try:  e.updateValue("postalAddress.countryLine.isoCode", "us")

**Comment by ASchmidt84** [comment]
This works fine
```
PatientViewFX(,PersonalDataFX(,,),PostalAddressFX(,,,,,,Deutschland),LocalDateFX(1970-01-01),EmailAddressFX(),inactive,PhoneNumberFX(),PhoneNumberFX(),PhoneNumberFX(),PhoneNumberFX(),,PatientPictureFX(None,),Keine Angabe)
PatientViewFX(,PersonalDataFX(,,),PostalAddressFX(,,,,,,Vereinigte Staaten),LocalDateFX(1970-01-01),EmailAddressFX(),inactive,PhoneNumberFX(),PhoneNumberFX(),PhoneNumberFX(),PhoneNumberFX(),,PatientPictureFX(None,),Keine Angabe)
```
That work. But update a custom data type not 😢

**Comment by sfxcode** [comment]
Found it, looking for the best way to implement ....

**Comment by sfxcode** [comment]
Hi,

Fixed in 1.0.7 (hopefully)

```
dependencyOverrides += "com.sfxcode.sapphire" %% "sapphire-data" % "1.0.7"
```

Have a nice coding weekend,

Greetings Tom

**Comment by sfxcode** [comment]
```
  val adapter = DataAdapter[ParentBean](ParentBean())

      adapter.getValue("child.address.street").toString must be equalTo "oldStreet"

      adapter.updateValue("child.address", Address("newStreet"))

      val street = adapter.wrappedData.child.address.street

      street must be equalTo "newStreet"

      val address = adapter.getValue("child.address").asInstanceOf[Address]

      address.street must be equalTo "newStreet"

      adapter.getValue("child.address.street").toString must be equalTo "newStreet"

      adapter.hasChanges must beTrue

      adapter.updateValue("child", ChildBean("name2", Address("street2")))
      adapter.getValue("child.address.street").toString must be equalTo "street2"
      adapter.getValue("child.childName").toString must be equalTo "name2"

      adapter.hasChanges must beTrue
```

**Comment by ASchmidt84** [comment]
Dear Tom, you did it 👍 💯 🥇 

Great job! Now it is working like expected!
I think it would be a good idea to push it into main 😄 

Have a nice weekend too

**Comment by sfxcode** [comment]
Youre welcome,

thank you for helping making this project better.

I have some small additions for DataAdapter in the pipeline but i will  integrate this into javafx until monday.

I am very interested in your usage of sapphire-javafx. Maybe you can send me some short description of your project or some screenshots to tom@sfxcode.com .

Happy coding,

Tom

**Comment by ASchmidt84** [comment]
Of course! 
Mail is on the way.
In Germany we have Heilpraktiker, that means their are like medics and treats persons. They cannot give hard drugs. For more information we can write. But the problem is, I found all the time very slow or expensive software for documentation the patient history, the consultings and the treatments. So I build a software for all OS and - in this moment - for free using. 

here a few pics also for other who might be interessted 😄 

![grafik](https://user-images.githubusercontent.com/5076186/111900795-c7cd8700-8a34-11eb-93c8-407203b08ec0.png)
![grafik](https://user-images.githubusercontent.com/5076186/111900796-ca2fe100-8a34-11eb-91a0-8161d485661c.png)
![grafik](https://user-images.githubusercontent.com/5076186/111900799-cdc36800-8a34-11eb-8343-b1de29494d74.png)

**Comment by sfxcode** [comment]
Hi,

very nice Application usage. Hope you have great effort with it.

Tom
